AuctionsTableIAM:
  Effect: Allow
  Action:
    - dynamoDb:PutItem
    - dynamoDb:Scan
    - dynamoDb:GetItem
    - dynamoDb:UpdateItem
    - dynamoDb:Query
  Resource:
    - ${self:custom.AuctionsTable.arn}
    - !Join [
        "/",
        ["${self:custom.AuctionsTable.arn}", "index", "statusAndEndDate"],
      ]
